### ISSUE TITLE
Software which worked on Pico-ResTouch-LCD-2.8 runs out of memory on a Pico-ResTouch-LCD-3.5 display

### ISSUE THREAD

**Issue by bianc104** [peterhinch/micropython-touch#16]
Hello, I've recently begun porting a piece of tested functional software from a Raspberry Pi Pico with a Pico-ResTouch-LCD-2.8 touch screen display to a Raspberry Pi Pico with a Pico-ResTouch-LCD-3.5 touch screen display. Once I properly adjusted the hardware_setup.py to match the new display (copied from the library, and then adjusted to rotate and match the default direction of the 2.8 display (vertical). While I've not adjusted the interface to utilize the increased space, there is no overflow that I can tell.

Unfortunately, the application seems prone to inconsistently and unpredictably crash when a scene change occurs. It does not seem to be consistently the same scene, or in the same instance of switching to a scene, however the error produced is consistently "MemoryError: memory allocation failed". Here is an example:
```
Task exception wasn't retrieved
future: <Task> coro= <generator object 'import_data' at 2003df30>
Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 740, in import_data
  File "<stdin>", line 557, in enter_password
  File "gui/core/tgui.py", line 192, in change
  File "<stdin>", line 187, in __init__
  File "<stdin>", line 70, in __init__
  File "gui/widgets/textbox.py", line 45, in __init__
MemoryError: memory allocation failed, allocating 376 bytes
```

After adding mem_info() calls at every scene change, I've not been able to easily identify any obvious consistent leaks or issues to correlate with my code. I also added gc.collect() calls in case it was not freeing memory quickly enough, but that does not appear to have resolved the issue. Again, the only difference appears to be the larger screen and respective changes to hardware_setup.py.

Do you have any ideas what I can look at to further troubleshoot this? Imports appear to take up roughly 75% of system memory on application start, but outside of the hardware configuration file, that has been unchanged. Could this be a result of a difference in the display drivers?

**Comment by peterhinch** [comment]
The increase in display size implies a larger frame buffer (from 38,400 to 76,800 bytes) hence your problems. One solution would be to move to a Pico 2 which has more RAM. Alternatively frozen bytecode can save RAM. In particular fonts consume almost no RAM when frozen. It is possible to freeze the entire GUI, although I leave `hardware_setup.py` and the application code unfrozen for flexibility.

**Comment by bianc104** [comment]
Thanks for the answer!

I worked out building and deploying base MicroPython, but when I copied the given build scripts (modifying the paths to match my environment) it seems to try to include the libraries in the build process but when I load the firmware onto the Pico and try to run the code without the GUI folder in the Pico filesystem, it cannot import it. Is there some step that I would seem to be missing? Do I need to change imports in my code? Any help would be greatly appreciated!

**Comment by peterhinch** [comment]
The GUI is a Python package so the directory structure must be retained. The approved way to freeze bytecode is to use manifests, but the quick and dirty way is as follows. Assuming you have the micropython source tree on your PC, go to the directory `ports/rp2/modules`. In that directory place a symlink called `gui` which points to the `gui` directory on your PC.

On my machine:
```bash
[adminpete@meerkat]: ~/micropython/ports/rp2/modules
$ ln -s /mnt/qnap2/data/Projects/MicroPython/micropython-touch/gui gui
```
Rebuild and GUI, fonts, demos and widgets will be frozen.

**Comment by bianc104** [comment]
Just as a follow up, I was able to freeze this as you suggested, and I did have some memory gains, but it still was over the available memory. We opted to test with a Pico 2 and found that it worked more or less flawlessly on that, so we moved ahead with that instead.

Thank you for the assistance, however!
