### ISSUE TITLE
reset_mpy() has no effect on operation.

### ISSUE THREAD

**Issue by zoland** [peterhinch/micropython-touch#20]
reset_mpy() has no effect on operation.

```
class CST820(ABCTouch):
    
    def __init__(self, i2c, rst, ssd, addr=0x15):
        super().__init__(ssd, None)
        self.i2c  = i2c
        self.addr = addr
        self.rst  = rst
        
        self.reset_mpy()
        
        i2c.writeto_mem(addr, 0xfe, b'\xff') # prohibit automatic switching to low-power mode
        # i2c.writeto_mem(addr, 0xfe, b'\x01') # Or should it be this???
        
        print("Chip_type: {:02X}".format(self.version()))


    def acquire(self, buf=bytearray(6)):  
        self.i2c.readfrom_mem_into(self.addr, 0x01, buf)
        self._x = ((buf[2] & 0xF) << 8) + buf[3]
        self._y = ((buf[4] & 0xF) << 8) + buf[5]
        
        print(f'Gest: {buf[0]} Touches: {buf[1]} Event {buf[2] & 0x40}: {self._x} {self._y}')

        return buf[1]


    def version(self):
        return self.i2c.readfrom_mem(self.addr, 0xA7, 1)[0]
    
    def reset_mpy(self):
        """Perform reset: Low=initialization, High=normal operation."""
        self.rst.off()
        sleep_ms(5)
        self.rst.on()
        sleep_ms(50)

```

This variant work with setup.py and check.py, but not work with checkbox.py

```
MPY: soft reboot
Chip_type: B7
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "gui/core/tgui.py", line 12, in <module>
  File "gui/core/colors.py", line 5, in <module>
  File "hardware_setup.py", line 62, in <module>
ImportError: can't import name Display
>>> 
```

in hardware_setup.py
---------------------
62: from gui.core.tgui import Display
63: display = Display(ssd, tpad)

_Originally posted by @zoland in https://github.com/peterhinch/micropython-touch/issues/19#issuecomment-2558523295_

**Comment by zoland** [comment]
This is result. In CST820 no Gesture, no events, but 0,1,2 fingers.
